baseURL = "https://zecc.sh/"
languageCode = "en-us"
title = "Ethan Decarli Zeccola | zecc.sh"
theme="archie"
copyright = ""
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourDisqusShortname"

paginate=8 # articles per page

[params]
        mode="dark" # color-mode â†’ light,dark,toggle or auto
        useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
        subtitle = "Having fun surfing the World Wide Web."
        mathjax = true # enable MathJax support
        katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/rat-blue"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ethan_zeccola"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/ethan-decarli-zeccola-526054210/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
